# Generated by Django 4.0.3 on 2022-03-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_follow_remove_like_likes_like_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='kind',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('post', 'Post')], max_length=10),
        ),
    ]
