# Generated by Django 4.0.3 on 2022-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
