# Generated by Django 4.0.3 on 2022-03-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restifyuser",
            name="avatar",
            field=models.ImageField(upload_to="avatars/"),
        ),
    ]
